---

- hosts: all
  become: true
  roles:
    - role: wp.prerequis

- hosts: web
  become: true
  roles:
    - role: wp.php
    - role: wp.nginx

- hosts: data
  become: true
  roles:
    - role: wp.mysql
