---

- hosts: wordpress
  become: true
  roles:
    - role: wp.php
    - role: wp.mysql
    - role: wp.nginx
    - role: wp.wordpress
      database_name: wordpressdb
      database_user: wordpressusr
      database_password: bananas1234
