---
# tasks file for wp.wordpress
- name: Get WordPress checksum
  uri:
    url: https://wordpress.org/latest.zip.sha1
    return_content: true
  register: wp_checksum

- name: Download Wordpress
  get_url:
    url: https://wordpress.org/latest.zip
    dest: /tmp/wordpress.zip
    checksum: "sha1:{{wp_checksum.content}}"

- name: Unzip Wordpress
  unarchive:
    src: /tmp/wordpress.zip
    dest: /var/www
    remote_src: yes
    creates: /var/www/wordpress/wp-settings.php

- name: Create wp-config
  template:
    src: templates/wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
